version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    build: .
    ports:
      - '5000:5000'
    env_file: dev.env
  web:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
